apiVersion: batch/v1
kind: Job
metadata:
  name: bookapp-job
spec:
  template:
    spec:
      containers:
      - name: bookapp-job
        image: yash5090/bookapp:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
