apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: bookapp
  template:
    metadata:
      labels:
        app: bookapp
    spec:
      containers:
        - name: bookapp
          image: yash5090/bookapp:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
